[package]
name = "boovy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.1"
bevy_obj = "*"
bevy_xpbd_3d = "0.4.2"
bevy-inspector-egui = "0.23.1"
winit = "0.28"
image = "0.24.0"
bevy_third_person_camera = { path = "src/CThirdCam" }
strum = "0.26"
strum_macros = "0.26"


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
